/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import Metodos_sql.Metodos_sql;
import javax.swing.JOptionPane;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class registrarse extends javax.swing.JFrame {

    private String nombre;
    private String apellidos;
    private String correo;
    private String contraseña;

    private String alerta = "";

    private void setNombre(String nombre) {
        this.nombre = this.validarCampo(nombre, "Nombre");
    }

    private void setApellidos(String apellidos) {
        this.apellidos = this.validarCampo(apellidos, "Apellidos");
    }

    private void setCorreo(String correo) {

        Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        Matcher mather = pattern.matcher(correo);

        if (!correo.isEmpty()) {
            if (mather.find() == true) {
                this.correo = correo;
            } else {
                this.alerta += "Correo: Ingresa un correo valido" + "\n";
            }
        } else {
            this.alerta += "Correo: Ingresa algun valor" + "\n";
        }

    }

    private void setContraseña(String contraseña) {

        if (!contraseña.isEmpty()) {
            this.contraseña = contraseña;
        }else{
            this.alerta += "Contraseña: Ingresa algun valor" + "\n";
        }

    }

    public void setAlerta(String alerta) {
        this.alerta = alerta;
    }

    private String validarCampo(String valor, String campo) {
        boolean format = true;
        String texto = "";
        if (!valor.isEmpty()) {
            for (int x = 0; x < valor.length(); x++) {
                char c = valor.charAt(x);
                // Si no está entre a y z, ni entre A y Z, ni es un espacio
                if (!((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == ' ')) {
                    format = false;
                }
            }
            if (format == false) {
                this.alerta += campo + ": Ingresa unicamente letras" + "\n";
            } else {
                texto = valor;
            }
        } else {
            this.alerta += campo + ": Ingresa algun valor" + "\n";
        }
        return texto;
    }

    private String verAlerta() {
        return this.alerta;
    }

    private boolean registrarUsuario() {
        boolean valid = false;
        int valor;
        valor = metodos.guardar(this.nombre, this.apellidos, this.correo, this.contraseña);
        if (valor == 0) {
            valid = true;
        }
        return valid;
    }

    /**
     * Creates new form registrarse
     */
    public registrarse() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
// instanciamos la clase
    Metodos_sql metodos = new Metodos_sql();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REGISTRATE");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(520, 80, 155, 29);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Usuario / Correo :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(740, 230, 160, 22);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Contraseña :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(780, 300, 112, 22);

        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCorreo);
        txtCorreo.setBounds(900, 230, 226, 26);

        btnRegresar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnRegresar.setText("LOGIN");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar);
        btnRegresar.setBounds(800, 500, 109, 37);

        btnGuardar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnGuardar.setText("registar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar);
        btnGuardar.setBounds(1010, 500, 119, 37);
        jPanel1.add(txtContraseña);
        txtContraseña.setBounds(900, 300, 226, 26);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/certus2.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 740, 660);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Nombres:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(780, 120, 100, 22);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Apellidos:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(800, 170, 120, 22);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre);
        txtNombre.setBounds(900, 110, 230, 26);
        jPanel1.add(txtApellidos);
        txtApellidos.setBounds(900, 170, 230, 26);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        this.setNombre(txtNombre.getText());
        this.setApellidos(txtApellidos.getText());
        this.setCorreo(txtCorreo.getText());
        this.setContraseña(txtContraseña.getText());

        if (this.verAlerta().length() < 1) {
            if (this.registrarUsuario() == true) {
                JOptionPane.showMessageDialog(this, "registro realizado correctamente");

            } else if (this.registrarUsuario() == false) {
                JOptionPane.showMessageDialog(this, "no se pudo guardar correctamente los datos" + "\n" + this.verAlerta());

            }
        } else {
            {
                JOptionPane.showMessageDialog(this, this.verAlerta());
                this.setAlerta("");
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

        login login = new login();
        login.setVisible(true);
        dispose();


    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrarse.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrarse.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrarse.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrarse.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

}
